version: "3"

services:
  activemq:
    build:
      context: ./activemq
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      ACTIVEMQ_CONFIG_MINMEMORY: 1024
      ACTIVEMQ_CONFIG_MAXMEMORY: 4096
    volumes:
      - ./data:/data
      - ./log:/var/log/activemq
    restart: always
    container_name: activemq
